#!/bin/bash

VRSN="9.1"
rm -f /Library/Frameworks/Tcl.framework/Versions/Current
ln -s ${VRSN} /Library/Frameworks/Tcl.framework/Versions/Current
rm -f /usr/local/bin/tclsh
ln -s tclsh${VRSN} /usr/local/bin/tclsh

